# Generated by Django 4.2 on 2023-04-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='link',
            field=models.CharField(default='/', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='menucategories',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_item', to='menu.menucategories', verbose_name='Родительский пункт'),
        ),
    ]
